### PR TITLE
Adds support for kafka and boltdb pipelines

### PR DESCRIPTION
**Pull request by butschster**
### Create `kafka` pipeline

```php
use Spiral\RoadRunner\Jobs\Queue\KafkaCreateInfo;
use Spiral\RoadRunner\Jobs\Jobs;

$jobs = new Jobs(RPC::create('tcp://127.0.0.1:6001'));

$kafkaCreateInfo = new KafkaCreateInfo(
     name: 'kafka-queue',
     topic: 'subscription',
     maxOpenRequests: 1000
);

$queue = $jobs->create($kafkaCreateInfo);
```

### Push job into `kafka` pipeline

```php
use Spiral\RoadRunner\Jobs\KafkaOptions;
use Spiral\RoadRunner\Jobs\Queue\Kafka\PartitionOffset;

$queue->dispatch(
      $queue->create(
            'job:name',
            ['foo' => 'bar'],
            new KafkaOptions(
                  topic: 'some-topic',
                  metadata: 'foo-bar',
                  offset: PartitionOffset::OFFSET_NEWEST
            )
      )
);
```

#### Changing options in a prepared task:
```php
$queue = $jobs->create($kafkaCreateInfo);
        
$task = $queue->create(
    'job:name',
    ['foo' => 'bar'],
    new KafkaOptions(
        topic: 'some-topic',
        metadata: 'foo-bar',
        offset: PartitionOffset::OFFSET_NEWEST
    )
);
        
$queue->dispatch($task->withOptions(new KafkaOptions(
    topic: 'other',
    metadata: 'foo-bar',
    offset: PartitionOffset::OFFSET_NEWEST
)));

$queue->dispatch($task->withOptions($task->getOptions()->withTopic('other')));
$queue->dispatch($task->withDelay(10));
```
---

### Create `boltdb` pipeline

```php
use Spiral\RoadRunner\Jobs\Queue\BoltdbCreateInfo;
use Spiral\RoadRunner\Jobs\Jobs;

$jobs = new Jobs(RPC::create('tcp://127.0.0.1:6001'));

$boltdbCreateInfo = new BoltdbCreateInfo(
     name: 'boltdb-queue',
     file: 'rr.db'
);

$queue = $jobs->create($boltdbCreateInfo);
```

### CODE REVIEW

**Comment by rustatian** [comment]
image
That is the data coming from the PHP. No topic and very strange payload.

**Comment by msmakouz** [comment]
@Baiquette Hi,
If you are using the `connect` method from the `Jobs` class, you must pass the `KafkaOptions` object as the second parameter. It will be used as the default options. For example:

```php
$jobs = new Jobs(RPC::create('tcp://127.0.0.1:6001'), new JsonSerializer());
$queue = $jobs->connect('test-kafka', new KafkaOptions(topic: 'mytopic', offset: PartitionOffset::OFFSET_NEWEST));
```

If you haven't done so, a base class named `Options` will be created and will not have options that are specific to Kafka. When submitting a job, the passed options are merged with the default options, but since the default options are `Options`, some of the options with `KafkaOptions` are lost.

You can pass a serializer as the second parameter to `Jobs` and `Consumer`: 
```php
$consumer = new Consumer(serializer: new JsonSerializer());
```
With PHP 8.1 this is mandatory because the default serializer is based on `opis/closure` and it doesn't work with PHP 8.1 (we removed it, but this PR:  https://github.com/spiral/roadrunner-jobs/pull/19/files isn't merged).

I created a simple example here:
https://github.com/msmakouz/roadrunner-kafka-example

**Comment by Baiquette** [comment]
Hi @msmakouz 
Thank you for explanations, it works fine now! :)

**Review by rustatian — APPROVED** [review]
LGTM

**Pull request merged**
